name: Justin A Ellis
description: Justin's Website

url: "[http://localhost:4000]"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments

footer-links:
    twitter: justinellis18
    facebook: justin.ellis.7967
    github: jellis18

pages_list:
    Research: '/research'
    Cirriculum Vitae: '/files/cv.pdf'
    Publications: '/publications'
    Blog: '/blog'

defaults:
  -
    scope:
        path: "" # an empty string here means all files in the project
    values:
        layout: "default"
