# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

name: Rutger van Haasteren
description: Rutger's Website & Blog

url: "http://localhost:4000"

paginate_path: "/blog/page:num"

markdown: kramdown
permalink: pretty
highlighter: rouge

kramdown:
  input: GFM

footer-links:
  facebook: rutger.vanhaasteren
  github: vhaasteren

pages_list:
  Research: '/research'
  Resume: '/files/resume_vanhaasteren.pdf'
  Cirriculum Vitae: '/files/cv_vanhaasteren.pdf'
  Publications: '/publications'
  Blog: '/blog'

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
